/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "img.h"

int *
moyfiltr_prog_1_1_svc(argimg *argp, struct svc_req *rqstp)
{
	static int  result = 0;
	argimg * img = argp;
	int index;
	unsigned char * buffer = NULL;
	int offset_V = (img->n)/2;
	int offset_H = (img->m)/2;
	int i, j, h, l;
	float somme = 0.0;
	
	buffer = malloc(sizeof(n*m*sizeof(unsigned char)));
	
	for(i=1; i< img->hauteur-1; i++){
		for(j=1; j < img->largeur-1; j++){
		somme = 0.0;
			for(h= -offset_H; h<= offset_H; h++){
				for(l= -offset_V; l<=offset_V; l++){
					somme+=img->imgE[i+h+img->largeur*(j+l)];
				}
			}
			img->imgS[i+j*img->largeur] = (unsigned char) (somme/(float)n*m);
		}
	}
	result = 1;
	return &result;
}

int *
medfiltr_prog_2_1_svc(argimg *argp, struct svc_req *rqstp)
{
	static int  result;

	/*
	 * insert server code here
	 */

	return &result;
}

int *
saveimg_prog_3_1_svc(argimg *argp, struct svc_req *rqstp)
{
	static int  result;

	/*
	 * insert server code here
	 */

	return &result;
}
